baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
#theme = 'benis'
#
[mediaTypes]
  [mediaTypes.'image/vnd.microsoft.icon']
      suffixes = ['ico']

#Why this option exists is explained her: https://github.com/gohugoio/hugo/issues/9315#issuecomment-1000347317
#it seems very niche and I don't believe it should be enabled by default
[security.exec]
allow = ['.*']
# security policy once again making life difficult for no damn reason
[security.http]
methods = ['(?i)GET|POST']
urls = ['.*']
contentTypes = ['.*']
mediaTypes = ['.*']
