baseURL = 'http://localhost'
languageCode = 'en-us'
title = 'CV - Jordan Conway McLaughlin'

[mediaTypes]
  [mediaTypes.'image/vnd.microsoft.icon']
      suffixes = ['ico']

#Why this option exists is explained here: https://github.com/gohugoio/hugo/issues/9315#issuecomment-1000347317
# while it's an impressive dedication to security, this an insane threat model for almost any real user
[security.exec]
allow = ['.*']
# security policy once again making life difficult for no reason
[security.http]
methods = ['(?i)GET|POST']
urls = ['.*']
contentTypes = ['.*']
mediaTypes = ['.*']
